-- ============================================================
-- MEDIDAS DE SELL-OUT
-- Módulo: 02_SELLOUT
-- ============================================================

-- Variação da demanda entre janelas móveis de 3 meses (L3M)
-- Compara os últimos 3 meses com os 3 meses imediatamente anteriores
-- Mais sensível a tendências recentes do que o YoY tradicional
L3M =
VAR ultimo_mes = MAX('00_COMUM_DIM_calendario'[Data])

-- Janela atual: últimos 3 meses a partir do mês corrente
VAR total_mes_atual =
    CALCULATE(
        [02_REALIZADO],
        DATESINPERIOD(
            '00_COMUM_DIM_calendario'[Data],
            EOMONTH(ultimo_mes, 0),
            -3,
            MONTH
        )
    )

-- Janela anterior: os 3 meses que precedem a janela atual
VAR total_mes_anterior =
    CALCULATE(
        [02_REALIZADO],
        DATESINPERIOD(
            '00_COMUM_DIM_calendario'[Data],
            EOMONTH(ultimo_mes, -3),
            -3,
            MONTH
        )
    )

RETURN
    DIVIDE(
        total_mes_atual - total_mes_anterior,
        total_mes_anterior,
        BLANK()
    )

-- Projeção do mês corrente baseada em dias úteis realizados
-- Fonte de referência: data de corte do Close-Up (auditoria externa)
--
-- Lógica:
--   Mês já fechado (anterior ao Close-Up) → retorna realizado direto
--   Mês corrente → extrapola o realizado proporcionalmente aos dias úteis
--
-- Padrão sofisticado: usa dias úteis (não dias corridos) como base de
-- extrapolação, ancorado na data de corte da auditoria Close-Up —
-- não em TODAY(). Isso evita distorções em meses com feriados e
-- garante consistência com a fonte oficial de dados de mercado.
Projeção calculada mês =
VAR DataCloseUp   = [Data Close-Up] - 1
VAR AnoRef        = YEAR(DataCloseUp)
VAR MesRef        = MONTH(DataCloseUp)

VAR AnoFiltro     = SELECTEDVALUE('00_COMUM_DIM_calendario'[Ano])
VAR MesFiltro     = SELECTEDVALUE('00_COMUM_DIM_calendario'[Mes])

-- Mês selecionado é anterior ao corte do Close-Up → já está fechado
VAR MesAnterior =
    (AnoFiltro < AnoRef) ||
    (AnoFiltro = AnoRef && MesFiltro < MesRef)

-- Dias úteis já transcorridos até a data de corte
VAR DiasUteisRealizados =
    CALCULATE(
        COUNTROWS('00_COMUM_DIM_calendario'),
        '00_COMUM_DIM_calendario'[flag_dia_util] = 1,
        '00_COMUM_DIM_calendario'[Data] <= DataCloseUp,
        '00_COMUM_DIM_calendario'[Ano]  = AnoRef,
        '00_COMUM_DIM_calendario'[Mes]  = MesRef
    )

-- Total de dias úteis do mês de referência
VAR DiasUteisDoMes =
    CALCULATE(
        COUNTROWS('00_COMUM_DIM_calendario'),
        '00_COMUM_DIM_calendario'[flag_dia_util] = 1,
        '00_COMUM_DIM_calendario'[Ano] = AnoRef,
        '00_COMUM_DIM_calendario'[Mes] = MesRef
    )

-- Taxa diária média baseada nos dias úteis realizados
VAR ProjecaoDiaria = DIVIDE([02_REALIZADO], DiasUteisRealizados)

RETURN
    IF(
        MesAnterior,
        [02_REALIZADO],            -- mês fechado: retorna realizado
        ProjecaoDiaria * DiasUteisDoMes  -- mês aberto: extrapola
    )

-- Data de corte da auditoria Close-Up
-- Remove todos os filtros de data para capturar o MAX global da tabela diária
-- Usada como âncora temporal em toda a lógica de projeção
Data Close-Up =
CALCULATE(
    MAX('02_SELLOUT_FATO_diario'[dt_periodo]),
    REMOVEFILTERS('02_SELLOUT_FATO_diario'[dt_periodo]),
    REMOVEFILTERS('00_COMUM_DIM_calendario'[MesAno])
)

-- L3M Ano Anterior com fallback para projeção
-- Problema: o mês equivalente do ano anterior pode não ter fechado ainda
-- Solução: detecta se existe realizado no mês AA; se não, substitui
-- apenas esse mês pela projeção — mantendo os outros 2 meses como realizado
-- Padrão: comparativo de janela móvel robusto a lag de dados históricos
Demanda L3M A.A =
VAR _data_contexto  = MAX('00_COMUM_DIM_calendario'[Data])
VAR _data_base_aa   = EOMONTH(EDATE(_data_contexto, -12), 0)
VAR _ano_aa         = YEAR(_data_base_aa)
VAR _mes_aa         = MONTH(_data_base_aa)

-- Verifica se o mês equivalente do ano anterior já tem dados fechados
VAR _tem_realizado_mes_aa =
    CALCULATE(
        COUNTROWS('02_SELLOUT_FATO_mensal'),
        REMOVEFILTERS('00_COMUM_DIM_calendario'),
        '00_COMUM_DIM_calendario'[Ano] = _ano_aa,
        '00_COMUM_DIM_calendario'[Mes] = _mes_aa
    ) > 0

-- L3M completo do ano anterior
VAR _realizado_l3m_aa =
    CALCULATE(
        [02_REALIZADO],
        DATESINPERIOD('00_COMUM_DIM_calendario'[Data], _data_base_aa, -3, MONTH)
    )

-- L3M do ano anterior sem o último mês (fallback parcial)
VAR _realizado_l3m_aa_sem_mes =
    CALCULATE(
        [02_REALIZADO],
        DATESINPERIOD('00_COMUM_DIM_calendario'[Data], EOMONTH(_data_base_aa, -1), -3, MONTH)
    )

-- Projeção do mês equivalente no ano anterior
VAR _projecao_mes_aa =
    CALCULATE(
        [02_PROJETADO],
        '00_COMUM_DIM_calendario'[Ano] = _ano_aa,
        '00_COMUM_DIM_calendario'[Mes] = _mes_aa
    )

RETURN
    IF(
        _tem_realizado_mes_aa,
        _realizado_l3m_aa,                              -- mês fechado: L3M completo
        _realizado_l3m_aa_sem_mes + _projecao_mes_aa    -- mês aberto: substitui só o mês faltante
    )
